{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "webconsul.serviceAccountName" . }}
  labels:
{{ include "webconsul.labels" . | indent 4 }}
{{- end -}}
